import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F4F4F4',
    // paddingTop wird dynamisch via SafeAreaInsets gesetzt
  },
  container: { flex: 1, backgroundColor: '#F4F4F4' },
  header: {
    // Kein paddingTop mehr, safe-area oben nur durch äußeren Container per useSafeAreaInsets
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: '#FAFAFA',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  headerTitle: { color: '#222', fontSize: 18, fontWeight: 'bold', marginLeft: 10, flex: 1 },
  backBtn: { padding: 8, backgroundColor: '#E0E0E0', borderRadius: 6 },
  btnText: { color: '#222', fontWeight: 'bold' },
  editBtn: { marginLeft: 10, padding: 8, backgroundColor: '#DDD', borderRadius: 6 },
  editBtnText: { color: '#222', fontWeight: 'bold' },
  songItem: { padding: 18, borderBottomWidth: 1, borderBottomColor: '#EBEBEB' },
  songTitle: { color: '#222', fontSize: 18, fontWeight: 'bold' },
  songArtist: { color: '#888', fontSize: 14, marginTop: 4 },
  lyricsContainer: { flex: 1, padding: 20 },
  lyricsText: { color: '#222', fontSize: 20, lineHeight: 32, fontFamily: 'monospace' },
  controlBar: {
    padding: 14,
    backgroundColor: '#FAFAFA',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    // paddingBottom für gestenleiste wird dynamisch hinzugefügt
  },
  controlBarEdit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    backgroundColor: '#FAFAFA',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    // paddingBottom für gestenleiste wird dynamisch hinzugefügt
  },
  controlBarEditTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    backgroundColor: '#FAFAFA',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  // --- Metronom Styles ---
  metronomeBar: {
    flexDirection: 'column',
    paddingTop: 8,
    paddingBottom: 8,
    paddingHorizontal: 18,
    backgroundColor: '#FCFCFC',
    borderBottomWidth: 1,
    borderBottomColor: '#E6E6E6',
  },
  // Eigene Zeile für Start/Pause + Mute, getrennt von BPM-Reglern/Blink-Kreis.
  metroTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  metroBottomRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    rowGap: 10,
  },
  metroBtn: {
    backgroundColor: '#E0E0E0',
    paddingVertical: 16,
    paddingHorizontal: 26,
    borderRadius: 12,
    marginRight: 18,
  },
  metroPlayActive: {
    backgroundColor: '#FFDF91',
  },
  metroBtnText: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 18,
  },
  bpmControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    rowGap: 10,
  },
  // Gleiche Größe wie die Zoom-Buttons im Menü (56x56, rund).
  bpmBtn: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#F1F1F1',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 4,
  },
  bpmBtnText: {
    color: '#333',
    fontSize: 20,
    fontWeight: 'bold',
  },
  bpmText: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 18,
    marginHorizontal: 12,
    minWidth: 78,
    textAlign: 'center'
  },
  // -- Mute/Unmute Metronom Button --
  metroMuteBtn: {
    backgroundColor: '#EFEFEF',
    width: 56,
    height: 56,
    borderRadius: 28,
    marginLeft: 12,
    borderWidth: 1,
    borderColor: '#DDD',
    justifyContent: 'center',
    alignItems: 'center'
  },
  metroMuted: {
    backgroundColor: '#FADADA',
    borderColor: '#C29797'
  },
  metroMuteIcon: {
    fontSize: 28,
    marginHorizontal: 0,
    color: '#7C6D6D'
  },
  playBtn: { backgroundColor: '#77DD77', paddingVertical: 10, paddingHorizontal: 20, borderRadius: 8 },
  playBtnActive: { backgroundColor: '#FF7B7B' },
  playBtnText: { color: '#222', fontWeight: 'bold', fontSize: 16 },
  speedControls: { flexDirection: 'row', alignItems: 'center' },
  speedBtn: { backgroundColor: '#E0E0E0', width: 36, height: 36, borderRadius: 18, justifyContent: 'center', alignItems: 'center' },
  speedBtnText: { color: '#222', fontSize: 17, fontWeight: 'bold' },
  speedText: { color: '#222', marginHorizontal: 12, fontSize: 16, fontWeight: 'bold' },
  transposeControls: { flexDirection: 'row', alignItems: 'center', marginRight: 16 },
  transposeBtn: { backgroundColor: '#E0E0E0', width: 32, height: 32, borderRadius: 16, justifyContent: 'center', alignItems: 'center', marginHorizontal: 4 },
  transposeBtnText: { color: '#222', fontWeight: 'bold', fontSize: 18 },
  transposeText: { color: '#222', marginHorizontal: 2, fontSize: 16, fontWeight: 'bold', minWidth: 28, textAlign: 'center' },
  scrollSpeedControls: { flexDirection: 'row', alignItems: 'center' },
  scrollSpeedBtn: { backgroundColor: '#E0E0E0', width: 30, height: 30, borderRadius: 15, justifyContent: 'center', alignItems: 'center' },
  scrollSpeedBtnText: { color: '#222', fontSize: 16, fontWeight: 'bold' },
  scrollSpeedText: { color: '#222', marginHorizontal: 6, fontSize: 14, fontWeight: 'bold', minWidth: 24, textAlign: 'center' },
  label: { color: '#222', fontSize: 15, marginTop: 12, marginBottom: 4 },
  helperText: { color: '#888', fontSize: 12, marginBottom: 8 },
  input: { backgroundColor: '#FFF', color: '#222', fontSize: 17, borderRadius: 6, padding: 10, marginBottom: 6 },
  lyricsEditInput: { minHeight: 120, fontFamily: 'monospace', textAlignVertical: 'top' },
  fullEditInput: { minHeight: 400, fontFamily: 'monospace', textAlignVertical: 'top' },
  chordLine: { color: '#8B5E00', fontWeight: 'bold', fontFamily: 'monospace', lineHeight: 22 },
  chordRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginVertical: 2 },
  chordText: { color: '#8B5E00', fontWeight: 'bold' },
  fixedBadgesWrap: {
    position: 'absolute',
    top: 12,
    right: 12,
    zIndex: 10,
    elevation: 10,
    flexDirection: 'row',
  },
  fixedBadge: {
    backgroundColor: 'rgba(34,34,34,0.85)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
  },
  fixedBadgeSpacing: { marginLeft: 12 },
  fixedBadgeText: { color: '#FFF', fontSize: 26, fontWeight: 'bold' },
  // Warnhinweis: Badge zeigt einen Fallback-Wert (BPM) oder fehlt ganz (Key),
  // weil der zugehörige Tag im Songtext fehlt/ungültig ist.
  fixedBadgeWarning: { backgroundColor: '#DC2626' },
  cancelBtn: { backgroundColor: '#DDD', paddingVertical: 10, paddingHorizontal: 18, borderRadius: 8 },
  cancelBtnText: { color: '#222', fontWeight: 'bold', fontSize: 16 },
  saveBtn: { backgroundColor: '#77DD77', paddingVertical: 10, paddingHorizontal: 18, borderRadius: 8 },
  saveBtnText: { color: '#222', fontWeight: 'bold', fontSize: 16 },
});
